Repository curveball/a12n-server, pull requests merged in 2019-12, with the labels that each got.

#114 Create user API
  src/register/controller.ts
  src/user/controller/collection.ts
  src/user/formats/hal.ts
  src/user/service.ts
Labels: enhancement

#115 removed ENUM usertype, fixes.
  src/group/service.ts
  src/register/controller.ts
  src/user/controller/collection.ts
  src/user/formats/hal.ts
  src/user/service.ts
  src/user/types.ts
Labels: enhancement

#123 requried, optional, disable addition to the '2FA' field
  mysql-schema/030-totp-setting.sql
  src/home/formats/hal.ts
  src/login/controller.ts
  src/login/formats/html.ts
  src/oauth2/controller/authorize.ts
  templates/login.hbs
Labels: enhancement

#125 Update all dependencies
  package-lock.json
  package.json
Labels: enhancement

#131 bug fix for 'activate' flag not working
  src/create-user/controller.ts
  templates/create-user.hbs
Labels: bug

#133 Allow typing of getSetting and remove debug code
  src/oauth2/service.ts
  src/server-settings.ts
Labels: bug, enhancement

#132 adding TOTP options
  src/oauth2/controller/authorize.ts
  src/oauth2/formats/html.ts
Labels: bug

#137 Require "admin" privileges for creating new users.
  src/create-user/controller.ts
  src/log/controller/user.ts
  src/privilege/service.ts
  src/user/controller/collection.ts
Labels: enhancement

#138 The OAuth2 token service now uses a full User object instead of just id
  src/introspect/controller.ts
  src/introspect/formats/json.ts
  src/middleware/login.ts
  src/oauth2/controller/validate-bearer.ts
  src/oauth2/controller/validate-totp.ts
  src/oauth2/service.ts
  src/oauth2/types.ts
  src/user/service.ts
Labels: bug
