Repository curveball/a12n-server, pull requests merged in 2020-12, with the labels that each got.

#211 Update dependencies
  .eslintrc.json
  package-lock.json
  package.json
  src/main-mw.ts
Labels: dependencies

#212 Adding some HTTP method hints
  src/home/formats/hal.ts
Labels: enhancement

#214 fix for `continue` query params.
  src/logout/controller.ts
Labels: bug

#215 Prep for 0.14.2 release
  changelog.md
  package-lock.json
  package.json
Labels: dependencies

#216 These types packages are no longer needed
  package-lock.json
  package.json
Labels: dependencies
