Repository curveball/a12n-server, pull requests merged in 2021-02, with the labels that each got.

#227 Support for 'password' grant_type in form
  src/oauth2-client/controller/collection.ts
  src/oauth2-client/formats/siren.ts
Labels: enhancement

#228 Release 0.15
  changelog.md
  package-lock.json
  package.json
Labels: dependencies

#231 accepts full url instead of only rel url.
  package-lock.json
  package.json
  src/group/controller/collection.ts
  src/user/service.ts
  test/user/service.ts
Labels: enhancement

#232 Update to the latest curveball APIs
  package-lock.json
  package.json
  src/blob/controller.ts
  src/changepassword/controller.ts
  src/group/controller/collection.ts
  src/log/controller/user.ts
  src/login/controller/login.ts
  src/login/controller/mfa.ts
  src/logout/controller.ts
  src/mfa/totp/controller/register.ts
  src/mfa/webauthn/controller/attestation.ts
  src/mfa/webauthn/controller/login.ts
  src/mfa/webauthn/controller/register.ts
  src/middleware/login.ts
  src/oauth2-client/controller/collection.ts
  src/oauth2-client/controller/item.ts
  src/oauth2-client/controller/new.ts
  src/oauth2/controller/authorize.ts
  src/privilege/controller/item.ts
  src/register/controller/mfa.ts
  src/register/controller/user.ts
  src/reset-password/controller/reset-password.ts
  src/reset-password/controller/token.ts
  src/user/controller/item.ts
  test/oauth2/controller/authorize.ts
Labels: enhancement

#237 Update everything to latest curveball standards
  .github/CODE_OF_CONDUCT.md
  .github/dependabot.yml
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
  .travis.yml
  package-lock.json
  package.json
  src/app.ts
  src/blob/controller.ts
  src/database.ts
  src/introspect/formats/json.ts
  src/log/formats/csv.ts
  src/login/controller/login.ts
  src/login/controller/mfa.ts
  src/mfa/totp/controller/register.ts
  src/oauth2-client/controller/collection.ts
  src/oauth2-client/service.ts
  src/oauth2/controller/authorize.ts
  src/oauth2/service.ts
  src/reset-password/service.ts
  src/templates.ts
  src/user/service.ts
  test/oauth2/controller/authorize.ts
  tsconfig.json
Labels: enhancement

#235 one time token for user invitation
  package-lock.json
  package.json
  src/one-time-token/controller.ts
  src/one-time-token/formats/hal.ts
  src/one-time-token/service.ts
  src/one-time-token/types.ts
  src/reset-password/controller/request.ts
  src/reset-password/controller/token.ts
  src/reset-password/service.ts
  src/routes.ts
  src/user/formats/hal.ts
Labels: enhancement

#241 one-time token bug fix
  package-lock.json
  src/one-time-token/controller.ts
Labels: bug

#242 Add 'login.defaultRedirect'
  mysql-schema/041-default-landing-page.sql
  src/login/controller/login.ts
  src/server-settings.ts
Labels: enhancement

#244 Logging was broken since the update to the new session system.
  src/log/service.ts
Labels: bug
