Repository curveball/a12n-server, pull requests merged in 2021-05, with the labels that each got.

#316 More eslint rules
  .eslintrc.json
  src/log/service.ts
  src/log/types.ts
  src/login/controller/login.ts
  src/mfa/types.ts
  src/mfa/webauthn/service.ts
  src/mfa/webauthn/types.ts
  src/oauth2-client/parse-basic-auth.ts
  src/oauth2-client/service.ts
  src/oauth2-client/types.ts
  src/oauth2/formats/json.ts
  src/oauth2/jwt.ts
  src/oauth2/service.ts
  src/oauth2/types.ts
  src/principal/service.ts
  src/principal/types.ts
  src/privilege/service.ts
  src/privilege/types.ts
  src/server-settings.ts
  src/templates.ts
Labels: enhancement

#317 Change ADD NEW APP url from /app/new (404) → /create-user
  src/app/formats/hal.ts
Labels: bug

#318 Hide schema-collection from markdown homepage
  package-lock.json
  package.json
  src/home/formats/hal.ts
  src/main-mw.ts
Labels: enhancement

#320 Lots of style improvements to the a12nserver home doc
  assets/extra.css
  package-lock.json
  package.json
  src/blob/controller.ts
  src/home/controller.ts
  src/home/formats/hal.ts
  src/home/formats/markdown.ts
  src/home/service.ts
  src/main-mw.ts
  src/principal/service.ts
  src/privilege/service.ts
  src/types.ts
Labels: enhancement

#321 bug fix for `findHref` pointing at wrong table
  src/principal/service.ts
Labels: bug

#322 Allow members to be added/removed from groups with HAL form.
  changelog.md
  schemas/group-patch.json
  src/group/controller/item.ts
  src/group/formats/hal.ts
  src/group/service.ts
  src/user/controller/by-href.ts
  src/user/controller/item.ts
Labels: enhancement

#323 Releasing 0.19
  changelog.md
  package-lock.json
Labels: dependencies

#324 schema required fix
  package-lock.json
  schemas/group-patch.json
Labels: bug

#325 fix userHref to memberHref
  schemas/group-patch.json
  src/group/controller/member-collection.ts
  src/oauth2-client/formats/siren.ts
Labels: bug

#327 Fix schema uri
  changelog.md
  src/home/formats/markdown.ts
Labels: bug

#328 Add Curl to docker image
  Dockerfile
  changelog.md
Labels: enhancement

#329 fix patch on /group/:id
  changelog.md
  src/group/controller/item.ts
Labels: enhancement

#330 Don't show 'remove member' form if there are no members
  changelog.md
  src/group/formats/hal.ts
Labels: enhancement
