Repository curveball/a12n-server, pull requests merged in 2021-06, with the labels that each got.

#332 A new systems for settings.
  src/login/controller/login.ts
  src/main-mw.ts
  src/mfa/webauthn/controller/attestation.ts
  src/mfa/webauthn/controller/login.ts
  src/oauth2/jwt.ts
  src/oauth2/service.ts
  src/reset-password/service.ts
  src/server-settings.ts
Labels: enhancement

#334 Settings from database were ignored
  src/server-settings.ts
Labels: bug

#338 Test release branches
  .github/workflows/test.yml
Labels: enhancement

#339 Backport: Test release branches
  .github/workflows/test.yml
Labels: enhancement

#340 Preparing 0.19.7 release
  changelog.md
  package-lock.json
  package.json
Labels: dependencies, enhancement

#342 user search by href will redirect to the user
  package-lock.json
  src/user/controller/by-href.ts
Labels: bug

#344 user search by href will redirect to the user
  src/user/controller/by-href.ts
Labels: bug
